dist: bionic
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

#### PHP 7.4 && PHP 8
## Faker is not yet compatible
## https://github.com/fzaninotto/Faker/pull/1816/files

matrix:
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - yes '' | pecl install imagick
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
  - |
    if [[ -f 'tests/storage/logs/laravel.log' ]]; then
      curl -F "file=@tests/storage/logs/laravel.log" https://file.io\?expires\=1d
    fi
