dist: xenial
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

install:
  - yes '' | pecl install imagick
  - composer validate --strict
  - |
    if [[ "$TRAVIS_PHP_VERSION" == 'nightly' ]]; then
      travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist --ignore-platform-reqs
    else
      travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
    fi

script:
  - vendor/bin/php-cs-fixer --dry-run --config=./.php_cs.travis fix src/ tests/  || travis_terminate 1;
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then
      vendor/bin/phpunit --configuration phpunit-7.1.xml
    else
      vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    fi

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.4' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
  - |
    LOG_FILE=${TRAVIS_BUILD_DIR}/tests/storage/logs/laravel.log
    if [[ -f "$LOG_FILE" ]]; then
      cat $LOG_FILE
    fi
